from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from database import AsyncSessionLocal
from models.db_models import Seat, Order
from services.insight_service import generate_peak_insights
from typing import List, Dict

router = APIRouter(
    prefix="/analytics",
    tags=["analytics"]
)

async def get_db():
    async with AsyncSessionLocal() as session:
        yield session

def calculate_density_score(seat_data: List[Dict], order_data: List[Dict]) -> Dict:
    """
    Logic generated by DeepSeek Coder
    """
    heatmap = []
    queue_density = {}

    # Seat Heatmap Logic
    for seat in seat_data:
        if seat['status'] == 'occupied':
            # Score based on duration (cap at 60 mins for 1.0)
            score = min(seat['duration_minutes'] / 60.0, 1.0)
            heatmap.append({"seat_id": seat['seat_id'], "score": score})
        else:
            heatmap.append({"seat_id": seat['seat_id'], "score": 0.0})

    # Stall Queue Density Logic
    for stall in order_data:
        q_len = stall['queue_length']
        wait = stall['avg_wait_time']
        
        if q_len > 5 or wait > 10:
            density = 'High'
        elif q_len > 2:
            density = 'Medium'
        else:
            density = 'Low'
        
        queue_density[stall['stall_id']] = density

    return {'heatmap': heatmap, 'queue_density': queue_density}

@router.get("/density")
async def get_density_data(db: AsyncSession = Depends(get_db)):
    # 1. Fetch Seat Data
    seat_result = await db.execute(select(Seat))
    seats = seat_result.scalars().all()
    
    # Mock duration for demonstration (in real app, calculate from SeatHistory)
    seat_data = [
        {"seat_id": s.id, "status": s.status, "duration_minutes": 15 if s.status == "occupied" else 0} 
        for s in seats
    ]

    # 2. Mock Order/Queue Data (simulating shop status)
    order_data = [
        {"stall_id": 1, "queue_length": 6, "avg_wait_time": 12}, # High
        {"stall_id": 2, "queue_length": 3, "avg_wait_time": 5},  # Medium
        {"stall_id": 3, "queue_length": 1, "avg_wait_time": 2},  # Low
    ]

    # 3. Calculate using AI Logic
    density_result = calculate_density_score(seat_data, order_data)
    
    # 4. Generate AI Insights via Groq
    insights = await generate_peak_insights(density_result)
    
    return {
        "status": "success",
        "data": density_result,
        "insights": insights
    }
